# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Daruma Drop One")
        font.setPointSize(72)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("background-color: #252222;")
        self.W1 = QtWidgets.QWidget(MainWindow)
        self.W1.setObjectName("W1")
        self.logo1 = QtWidgets.QLabel(self.W1)
        self.logo1.setGeometry(QtCore.QRect(220, 70, 381, 91))
        self.logo1.setMinimumSize(QtCore.QSize(381, 0))
        self.logo1.setMaximumSize(QtCore.QSize(381, 16777215))
        font = QtGui.QFont()
        font.setFamily("Daruma Drop One")
        font.setPointSize(48)
        self.logo1.setFont(font)
        self.logo1.setStyleSheet("background-color: none;\n"
"font-size: 48 px;\n"
"color: #C42EE9;")
        self.logo1.setObjectName("logo1")
        self.label_3 = QtWidgets.QLabel(self.W1)
        self.label_3.setGeometry(QtCore.QRect(-40, 380, 301, 261))
        self.label_3.setStyleSheet("background-image: url(\"./icons/Ellipse_3.png\");\n"
"background-color: none;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.W1)
        self.textEdit.setGeometry(QtCore.QRect(540, 200, 291, 241))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textEdit.setStyleSheet("background-image: url(\"./icons/Ellipse_4.png\");\n"
"background-color: none;\n"
"border: none;")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.W1)
        self.label_2.setGeometry(QtCore.QRect(620, -30, 191, 171))
        self.label_2.setStyleSheet("background-image: url(\"./icons/Ellipse_2.png\");\n"
"background-color: none;\n"
"border: none;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.startbtn = QtWidgets.QPushButton(self.W1)
        self.startbtn.setGeometry(QtCore.QRect(275, 310, 250, 70))
        font = QtGui.QFont()
        font.setFamily("Comfortaa SemiBold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.startbtn.setFont(font)
        self.startbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startbtn.setAcceptDrops(False)
        self.startbtn.setStyleSheet("background-color: #C42EE9;\n"
"border-radius: 10px;\n"
"color: white;\n"
"")
        self.startbtn.setObjectName("startbtn")
        self.textEdit_2 = QtWidgets.QTextEdit(self.W1)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 130, 211, 211))
        self.textEdit_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textEdit_2.setStyleSheet("background-image: url(\"./icons/Ellipse_5.png\");\n"
"background-color: none;\n"
"border: none;")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2.raise_()
        self.logo1.raise_()
        self.label_3.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.startbtn.raise_()
        MainWindow.setCentralWidget(self.W1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kitten\'s Draw"))
        self.logo1.setText(_translate("MainWindow", "Kitten\'s Draw"))
        self.label_3.setWhatsThis(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"./icons/Ellipse_3.png\" /></p></body></html>"))
        self.startbtn.setText(_translate("MainWindow", "НАЧАТЬ"))
        self.textEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\"./icons/Ellipse_3.png\"/></p></body></html>"))
        self.textEdit_2.setWhatsThis(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
